# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_model',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='day_model',
            name='valid_to',
        ),
    ]
