# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0007_auto_20170912_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_exception',
            name='actioned_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
