# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0015_day_model_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='shift',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utils.Profile'),
        ),
        migrations.AlterField(
            model_name='shift_exception',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Profile'),
        ),
        migrations.AlterField(
            model_name='shift_sequence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Profile'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
