# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_profile_team_manager'),
        ('wfm', '0016_auto_20171204_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift_Exception_Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Profile')),
                ('shift_exception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfm.Shift_Exception')),
            ],
        ),
    ]
