# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0017_shift_exception_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shift_Exception_Notes',
            new_name='Shift_Exception_Note',
        ),
    ]
