# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0018_auto_20171206_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift_exception_note',
            old_name='created_on',
            new_name='created_time',
        ),
    ]
