# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0019_auto_20171206_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift_exception_note',
            name='note',
            field=models.CharField(default='Null', max_length=250),
            preserve_default=False,
        ),
    ]
