# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0020_shift_exception_note_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift_exception',
            name='submitted_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
