# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0021_shift_exception_submitted_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift_exception',
            name='approved',
        ),
        migrations.AddField(
            model_name='shift_exception',
            name='status',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
    ]
