# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0022_auto_20171207_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_exception',
            name='status',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
