# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0025_auto_20171212_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift_exception',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
