# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-15 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0026_shift_exception_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Profile'),
        ),
    ]
