# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-04 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0027_auto_20180614_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_exception',
            name='shift_sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wfm.Shift_Sequence'),
        ),
    ]
