# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-18 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_notification'),
        ('wfm', '0028_auto_20180704_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacation_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.CharField(max_length=250)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='shift_exception_note',
            name='note',
            field=models.TextField(),
        ),
    ]
