# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-18 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0029_auto_20180817_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation_tracker',
            name='profile',
        ),
        migrations.DeleteModel(
            name='vacation_tracker',
        ),
    ]
