# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-18 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0031_vacation_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation_tracker',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
