# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0002_auto_20170911_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_model',
            name='valid_from',
            field=models.DateField(default='2017-01-01'),
        ),
        migrations.AddField(
            model_name='day_model',
            name='valid_to',
            field=models.DateField(default='2017-12-31'),
        ),
    ]
