# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0004_auto_20170911_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_model',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='day_model',
            name='valid_to',
        ),
    ]
