# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 03:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wfm', '0006_auto_20170912_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift_exception',
            name='actioned_by',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift_exception',
            name='actioned_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='shift_exception',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee_number',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='extension',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wfm.Location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(blank=True, to='wfm.Skill'),
        ),
    ]
