# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0008_auto_20170912_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_exception',
            name='actioned_by',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
