# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 23:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wfm', '0010_shift_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=20)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('agents', models.TextField()),
                ('actioned_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('actioned_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
