# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('payments', models.IntegerField(blank=True)),
                ('branded', models.BooleanField()),
                ('hw_support_t1', models.BooleanField()),
                ('hw_support_t2', models.BooleanField()),
                ('domain', models.CharField(max_length=50)),
                ('wallet_number', models.CharField(max_length=15)),
                ('custom_contact_info', models.BooleanField()),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('chat_float_window', models.CharField(blank=True, max_length=50)),
                ('change_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Phone_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='payment_model',
            field=models.ManyToManyField(to='clients.Payment_Model'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_numbers',
            field=models.ManyToManyField(blank=True, to='clients.Phone_Number'),
        ),
        migrations.AddField(
            model_name='client',
            name='support_language',
            field=models.ManyToManyField(to='clients.Language'),
        ),
    ]
