# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_model',
            field=models.ManyToManyField(blank=True, to='clients.Payment_Model'),
        ),
        migrations.AlterField(
            model_name='client',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
