# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20180115_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_info',
            name='first_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client_info',
            name='first_registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='chat_float_window',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='payment_model',
            field=models.ManyToManyField(blank=True, null=True, to='clients.Payment_Model'),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='payments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='phone_numbers',
            field=models.ManyToManyField(blank=True, null=True, to='clients.Phone_Number'),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
