# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20180115_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_info',
            name='change_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
