# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0003_auto_20170911_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='day_model',
        ),
        migrations.AddField(
            model_name='shift',
            name='day_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wfm.Day_Model'),
            preserve_default=False,
        ),
    ]
