# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 23:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wfm', '0009_auto_20170912_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift_Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('start_diff', models.DecimalField(decimal_places=0, max_digits=1)),
                ('end_date_time', models.DateTimeField()),
                ('end_diff', models.DecimalField(decimal_places=0, max_digits=1)),
                ('actioned_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('actioned_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfm.Profile')),
            ],
        ),
    ]
