# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0012_auto_20171108_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='parameters',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
