# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quality_Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Quality_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quality_Form_Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Quality_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Quality_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.DecimalField(decimal_places=0, max_digits=2)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.Quality_Form')),
            ],
        ),
        migrations.AddField(
            model_name='quality_question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.Quality_Section'),
        ),
        migrations.AddField(
            model_name='quality_evaluation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.Quality_Question'),
        ),
    ]
