# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_quality_question_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('question', models.ManyToManyField(to='quality.Quality_Question')),
            ],
        ),
    ]
