# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20171212_1607'),
        ('quality', '0003_quality_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality_Form_Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Profile')),
            ],
        ),
    ]
