# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_quality_form_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality_evaluation',
            name='form_overview',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quality.Quality_Form_Overview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quality_form_evaluation',
            name='form_overview',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quality.Quality_Form_Overview'),
            preserve_default=False,
        ),
    ]
