# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_auto_20180601_0934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quality_Evaluation',
            new_name='Evaluation',
        ),
        migrations.RenameModel(
            old_name='Quality_Form',
            new_name='Form',
        ),
        migrations.RenameModel(
            old_name='Quality_Form_Evaluation',
            new_name='Form_Evaluation',
        ),
        migrations.RenameModel(
            old_name='Quality_Form_Overview',
            new_name='Form_Overview',
        ),
        migrations.RenameModel(
            old_name='Quality_Question',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Quality_Response',
            new_name='Response',
        ),
        migrations.RenameModel(
            old_name='Quality_Section',
            new_name='Section',
        ),
    ]
