# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_auto_20180601_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='value',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='form_evaluation',
            name='value',
            field=models.TextField(),
        ),
    ]
