# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-22 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_auto_20180605_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_overview',
            name='status',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
            preserve_default=False,
        ),
    ]
