# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170918_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
    ]
