# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20171204_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skill_level',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_level',
            field=models.ManyToManyField(blank=True, to='utils.Skill_Level'),
        ),
    ]
