# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_event_type_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='log',
            name='event_type',
        ),
        migrations.DeleteModel(
            name='Event_Type',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
